#Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
#1,5,12,22,35,51,70,92,117,145...

#It can be seen that P4+P7=22+70=92=P8. However, their difference, 70-22=48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D=|Pk-Pj| is minimised; what is the value of ?

import math


def pentagonalise(number):
    pentagonal = number*((3*number)-1)/2
    print(pentagonal)
    return(pentagonal)

def reversePentagonalise(number):
    # 0 = 3n^2-n-dePental
    original = (1+(math.sqrt(1+(24*number))))/6
    print(original)
    if(original%1>0):
        return False
    return True

count = 0
limit = 100
while True:
    if(count > limit):
        break

    print(count)
    reversePentagonalise(pentagonalise(count))

    count += 1
